export const DEFAULT_FEEDBACK = 'Look again. Count the equal parts.';
export const MISCONCEPTIONS = {
  "UNEQUAL_PARTS_COUNTED": "Look at the sizes. Are all the pieces equal?",
  "SWAP_NUM_DEN": "Bottom counts all the parts. Top counts the parts we take.",
  "SHADED_OVER_UNSHADED": "Bottom is parts in ALL, not the parts left over.",
  "UNSHADED_OVER_TOTAL": "Top is the shaded parts. Count the coloured ones.",
  "WRONG_TOTAL": "Count every equal part, shaded or not.",
  "ONLY_COUNT_ONE": "Count ALL the shaded parts, not just one.",
  "BIG_DENOM_BIG_FRACTION": "More pieces means smaller pieces. Check the bars.",
  "COUNT_PIECES_ONLY": "Compare the size of the pieces, not just the count.",
  "SAME_BOTTOM_COMPARE_SLIP": "Same-size pieces: more pieces means more.",
  "NO_EQUIVALENCE_IDEA": "Different names can show the same amount.",
  "EQUIV_ADD_NOT_MULT": "Cut every piece the same way: top and bottom both grow.",
  "EQUIV_CHANGE_ONE_NUMBER": "Change both numbers the same way to keep the amount.",
  "NOT_SIMPLEST": "Right amount! Can you group the pieces any more?",
  "SIMPLIFY_SUBTRACT": "Group the pieces; don't take the same number away.",
  "SIMPLIFY_WRONG": "Group by the same number on top and bottom.",
  "SIMPLIFY_WRONG_DIRECTION": "Simplest means fewer, bigger pieces.",
  "ADD_NUM_AND_DEN": "Pieces must be the same size. Add only the tops.",
  "ADD_NUM_KEEP_DEN_UNLIKE": "Different sizes? Cut both into same-size pieces first.",
  "ADD_DENOMINATORS": "The bottom names the piece size. It stays the same.",
  "ESTIMATE_OFF": "Does your answer fit between the two amounts?",
  "MULT_INSTEAD": "Adding pieces needs same-size pieces, not multiplying.",
  "IMPROPER_REMAINDER_MISUSE": "How many wholes? What is left over?",
  "WRONG_NUMBER_OF_GROUPS": "The bottom number tells how many equal groups.",
  "USED_WRONG_FRACTION": "Check which fraction the question asks for.",
  "OF_MEANS_ONE_PART": "Take ALL the groups the top number asks for.",
  "PAY_THE_DISCOUNT": "That is the discount. What do you PAY?",
  "NO_DISCOUNT_APPLIED": "Take the discount off the price first.",
  "PART_OVER_PART": "Compare to ALL the parts, not just the others.",
  "TIME_FRACTION_MISREAD": "An hour is 60 minutes. Split it into equal parts.",
  "COMPARE_UNLIKE_GUESS": "Cut both into same-size pieces, then compare.",
  "ADD_INSTEAD_OF_MULT": "\"Of\" means a part of a part. Try the grid.",
  "MULT_TOPS_ADD_BOTTOMS": "Multiply the tops AND multiply the bottoms.",
  "IGNORED_SECOND_FRACTION": "Use both fractions. Take a part of the part.",
  "MULT_ALWAYS_BIGGER": "A part of a part is smaller than the part.",
  "NO_SIZE_SENSE": "Estimate first. Is the answer bigger or smaller?",
  "MULTIPLY_INSTEAD": "Count how many pieces fit, don't multiply.",
  "USED_DEN_ONLY": "Count the pieces that fit in the WHOLE length.",
  "FLIPPED_WRONG_PART": "Which length is being cut into pieces?",
  "DIVIDE_ALWAYS_SMALLER": "Dividing by a fraction less than 1 gives more.",
  "ADD_WHOLE_AND_DEN": "Don't add. Count how many pieces fit.",
  "SUBTRACT_INSTEAD": "Cutting pieces is counting how many fit.",
  "ANSWERED_THE_OPPOSITE": "That is the part used. What is LEFT?",
  "SUBTRACTED_FRACTIONS": "Add the parts used, then take them from the whole.",
  "ADDED_FRACTIONS_OF_WHOLE": "Second step is a part of the REST, not the whole.",
  "OF_THE_WHOLE_NOT_REST": "Part of the rest is smaller than part of the whole.",
  "STOPPED_AFTER_FIRST_STEP": "There is one more step. Check the bar.",
  "HALF_OF_WHOLE": "Half of what? Look at the bar's rest.",
  "ANSWERED_AMOUNT_GIVEN": "That is what was given away. How many are left?",
  "UNDID_ONLY_ONE_STEP": "Undo both steps, one at a time.",
  "USED_ONLY_FIRST_FRACTION": "Two fractions were used. Undo both.",
  "MULT_THE_USED_FRACTIONS": "Work backwards from what is left.",
  "ADDED_BACK_FRACTIONS": "Left is a fraction of the whole. Which one?"
};
export const feedbackFor = (tag) => MISCONCEPTIONS[tag] || DEFAULT_FEEDBACK;
