import { LAB_A } from './beginner/labA.js';
import { LAB_B } from './beginner/labB.js';
import { LAB_C, LAB_D, CRAB_GAME } from './beginner/labCD.js';
import { FISHING } from './beginner/fishing.js';
import { PIZZA, HUNT, BRIDGE } from './games3.js';
import * as G7 from './games7.js';
import { BUILDER_LABS } from './builder/labs.js';
import { ADVANCED_LAB_A } from './advanced/labs.js';
import { BUILDER_LAB_C } from './builder/labC.js';
import { ADVANCED_LABS } from './advanced/labsBCD.js';
const choice = (id, prompt, correct, wrong, visual = { parts: 4, shaded: 2 }) => ({ id, prompt, narration: prompt, visual, options: [{ id: 'yes', text: correct }, ...wrong.map(([text, tag], i) => ({ id: `no${i}`, text, tag }))], correct: 'yes', hints: [{ text: 'Look at all the equal parts.', narration: 'Look at all the equal parts.' }], explain: 'That picture shows it clearly.', explainNarration: 'That picture shows it clearly.' });
const labs = (items) => items.map(([id, letter, title, icon, remember, intro, parts, shaded, guided, checks], i) => ({ id, letter, title, icon, remember, intro: { text: intro, narration: intro }, explore: { parts, shaded, checklist: [{ key: 'tap', label: 'Tap a piece', required: true }, { key: 'shade', label: 'Colour some parts', required: true }, { key: 'change', label: 'Change the number of parts', required: true }, { key: 'read', label: 'Read the fraction', required: true }] }, guided: guided.map((goal, n) => ({ id: `${id}-${n}`, goal, narration: goal })), checkin: checks }));
const rounds = (name, icon, items) => ({ title: name, icon, intro: `Build the picture, then answer ${name}.`, narration: `Build the picture, then answer ${name}.`, rounds: items.map(([prompt, answer, parts, shaded, ...wrong], i) => choice(`${name}-${i}`, prompt, answer, wrong, { parts, shaded })) });
const boss = (items) => items.map(([prompt, answer, parts, shaded, ...wrong], i) => choice(`boss-${i}`, prompt, answer, wrong, { parts, shaded }));

export const CONTENT = {
  beginner: {
    wonder: { title: 'Sunrise Shore', tagline: 'Can you fix the Lighthouse?', particles: ['💎', '✨', '🍕', '🌅'], beats: [
      { headline: 'The Crystal BROKE!', narration: 'A storm shattered the Lighthouse Crystal. Mei and Danish need to share the pieces fairly.' },
      { headline: 'Make your guess!', prompt: 'Cut it so four friends are happy!', narration: 'Cut it so four friends are happy!', go: 'Serve!' },
      { headline: 'Equal parts are fair!', narration: 'Fair shares need equal parts. That is the secret of every fraction!', cta: 'Start the Story' },
    ] },
    story: [
      ['The Night the Light Went Out', 'A storm cracked the Lighthouse Crystal! Mei found pieces on the beach. Some are big. Some are tiny. How do we put it back?', '💎', 'Lab A · Break the Crystal'],
      ['Danish’s Pizza Problem', 'Danish baked a pizza for four helpers. Mei got a tiny slice. Not fair! Otto said fair shares need equal parts.', '🍕', 'Lab A · Break the Crystal'],
      ['Every Piece Has a Name', 'One of two equal parts is a half. One of four is a quarter. The bottom counts all parts. The top counts what we take.', '🔢', 'Lab B · Name It'],
      ['Fractions Are Everywhere', 'The tide is half out. Quarter past six is on the clock. More pieces make smaller pieces!', '🌊', 'Lab D · Slice Race'],
    ],
    labs: labs([
      ['b-a', 'A', 'Break the Crystal', '💎', 'Equal parts make a whole.', 'Cut a whole into fair, equal pieces.', 4, 1, ['Make two equal parts.', 'Make three equal parts.', 'Make four equal parts.'], [choice('ba1', 'Which shows equal parts?', 'Four matching pieces', [['Four uneven pieces', 'UNEQUAL_PARTS_COUNTED'], ['Three pieces', 'WRONG_TOTAL']], { parts: 4, shaded: 4 }), choice('ba2', 'One equal part of four is called?', 'One quarter', [['Four quarters', 'ONLY_COUNT_ONE'], ['One half', 'WRONG_TOTAL']], { parts: 4, shaded: 1 })]],
      ['b-b', 'B', 'Name It', '🔢', 'Top takes. Bottom counts.', 'Shade parts and name the fraction.', 4, 2, ['Shade one of two.', 'Shade two of three.', 'Shade three of four.'], [choice('bb1', 'What fraction is three shaded parts of four?', '3/4', [['4/3', 'SWAP_NUM_DEN'], ['1/4', 'ONLY_COUNT_ONE']], { parts: 4, shaded: 3 }), choice('bb2', 'What does the bottom number count?', 'All equal parts', [['Only coloured parts', 'SHADED_OVER_UNSHADED'], ['Parts left over', 'UNSHADED_OVER_TOTAL']], { parts: 5, shaded: 2 })]],
      ['b-c', 'C', 'Shore Town', '🏖️', 'Fractions show real amounts.', 'Fill cups, clocks and beach flags.', 4, 2, ['Fill half a cup.', 'Make quarter past.', 'Show three quarters.'], [choice('bc1', 'One of two equal cup marks is full. What is it?', '1/2', [['2/1', 'SWAP_NUM_DEN'], ['1/3', 'WRONG_TOTAL']], { parts: 2, shaded: 1 }), choice('bc2', 'Quarter past is what part of an hour?', '1/4', [['1/2', 'WRONG_TOTAL'], ['4/1', 'SWAP_NUM_DEN']], { parts: 4, shaded: 1 })]],
      ['b-d', 'D', 'Slice Race', '🦀', 'More pieces means smaller pieces.', 'Race two fraction flags along the shore.', 4, 1, ['Make a half.', 'Make a third.', 'Compare a quarter and an eighth.'], [choice('bd1', 'Which is larger?', '1/3', [['1/5', 'BIG_DENOM_BIG_FRACTION'], ['They match', 'COUNT_PIECES_ONLY']], { parts: 3, shaded: 1 }), choice('bd2', 'Which is larger?', '1/2', [['1/4', 'BIG_DENOM_BIG_FRACTION'], ['They match', 'COUNT_PIECES_ONLY']], { parts: 4, shaded: 2 })]],
    ]),
    games: [rounds('Pizza Party Slicer', '🍕', [['Make fair halves.', '1/2', 2, 1, ['2/1', 'SWAP_NUM_DEN'], ['1/3', 'WRONG_TOTAL']], ['Serve three of four slices.', '3/4', 4, 3, ['4/3', 'SWAP_NUM_DEN'], ['1/4', 'ONLY_COUNT_ONE']], ['Serve two of three slices.', '2/3', 3, 2, ['3/2', 'SWAP_NUM_DEN'], ['1/3', 'ONLY_COUNT_ONE']]]), rounds('Fraction Fishing', '🎣', [['Catch one half.', '1/2', 2, 1, ['2/1', 'SWAP_NUM_DEN'], ['1/3', 'WRONG_TOTAL']], ['Catch three fourths.', '3/4', 4, 3, ['4/3', 'SWAP_NUM_DEN'], ['1/4', 'ONLY_COUNT_ONE']]]), rounds('Fraction Hunt', '🔎', [['Find a quarter.', '1/4', 4, 1, ['4/1', 'SWAP_NUM_DEN'], ['1/2', 'WRONG_TOTAL']], ['Find three quarters.', '3/4', 4, 3, ['1/4', 'ONLY_COUNT_ONE'], ['4/3', 'SWAP_NUM_DEN']]]), rounds('Crab Race', '🦀', [['Which goes farther?', '1/2', 4, 2, ['1/4', 'BIG_DENOM_BIG_FRACTION'], ['They match', 'COUNT_PIECES_ONLY']], ['Which goes farther?', '1/3', 6, 2, ['1/6', 'BIG_DENOM_BIG_FRACTION'], ['They match', 'COUNT_PIECES_ONLY']]])],
    boss: boss([['What fraction is shaded?', '2/5', 5, 2, ['5/2', 'SWAP_NUM_DEN'], ['2/3', 'WRONG_TOTAL']], ['Which picture shows fourths?', '4 equal parts', 4, 4, ['4 uneven parts', 'UNEQUAL_PARTS_COUNTED'], ['3 equal parts', 'WRONG_TOTAL']], ['What fraction shows three of four?', '3/4', 4, 3, ['4/3', 'SWAP_NUM_DEN'], ['1/4', 'ONLY_COUNT_ONE']], ['Which is bigger?', '1/3', 3, 1, ['1/5', 'BIG_DENOM_BIG_FRACTION'], ['Same', 'COUNT_PIECES_ONLY']], ['Which is a real fraction use?', '3/4 of a battery', 4, 3, ['A whole shoe', 'WRONG_TOTAL'], ['One ball', 'WRONG_TOTAL']], ['What should Otto say?', 'More pieces make smaller pieces.', 8, 1, ['Eighths are bigger', 'BIG_DENOM_BIG_FRACTION'], ['They are always equal', 'COUNT_PIECES_ONLY']]]),
    explain: ['Look at the whole.', 'Cut equal parts.', 'Count all parts.', 'Count chosen parts.'],
  },
  builder: {
    wonder: { title: 'Tidepool Reef', tagline: 'Can you save the Reef Café?', particles: ['🐚', '🧁', '✨', '🌊'], beats: [{ headline: 'The bowl is empty!', narration: 'The Reef Café needs exact scoops. Different fractions can make the same amount.' }, { headline: 'Fill the bowl!', prompt: 'Pick scoops that make one whole.', narration: 'Pick scoops that make one whole.', go: 'Mix!' }, { headline: 'Fraction twins!', narration: 'Different names can show the same amount. Let us build them.', cta: 'Start the Story' }] },
    story: [['A Café Emergency', 'The Reef Café bowl cracked. Mei needs exact scoops for every recipe. Otto says matching amounts can have different names.', '🧁', 'Lab A · Twin Wall'], ['The Same Amount', 'One half of a bar is the same amount as two quarters. Different cuts can still cover the same space.', '🟦', 'Lab A · Twin Wall'], ['Market Day', 'Danish packed shells in equal groups. Fractions help him cook, shop and share fairly.', '🐚', 'Lab C · Sale Shop'], ['A Bridge to Build', 'A reef bridge needs planks that fit exactly. Otto says cut pieces to the same size before adding.', '🌉', 'Lab D · Clock Rope']],
    labs: labs([
      ['m-a', 'A', 'Twin Wall', '🧱', 'Same amount, new name.', 'Build fraction twins on a wall.', 4, 2, ['Make one half.', 'Make two fourths.', 'Make three sixths.'], [choice('ma1', 'Which is a twin of one half?', '2/4', [['1/4', 'NO_EQUIVALENCE_IDEA'], ['3/4', 'NO_EQUIVALENCE_IDEA']], { parts: 4, shaded: 2 }), choice('ma2', 'Which is simplest?', '1/2', [['2/4', 'NOT_SIMPLEST'], ['4/2', 'SWAP_NUM_DEN']], { parts: 4, shaded: 2 })]],
      ['m-b', 'B', 'Kitchen Bench', '🧁', 'Match piece sizes first.', 'Use scoops to fill the bowl.', 6, 3, ['Fill one half.', 'Fill three fourths.', 'Make one whole.'], [choice('mb1', 'One half plus one quarter equals?', '3/4', [['2/6', 'ADD_NUM_AND_DEN'], ['1/6', 'ADD_DENOMINATORS']], { parts: 4, shaded: 3 }), choice('mb2', 'Before adding thirds and quarters, do what?', 'Make equal-size pieces', [['Add bottoms', 'ADD_DENOMINATORS'], ['Guess', 'ESTIMATE_OFF']], { parts: 12, shaded: 7 })]],
      ['m-c', 'C', 'Sale Shop', '🏷️', 'Groups show fractions of sets.', 'Pack beach-market goods in equal groups.', 5, 3, ['Group ten shells.', 'Take two of five groups.', 'Find a sale discount.'], [choice('mc1', 'What is 3/5 of 20 coins?', '12', [['4', 'OF_MEANS_ONE_PART'], ['15', 'USED_WRONG_FRACTION']], { parts: 5, shaded: 3 }), choice('mc2', 'A 24-coin hat is one third off. Pay?', '16', [['8', 'PAY_THE_DISCOUNT'], ['24', 'NO_DISCOUNT_APPLIED']], { parts: 3, shaded: 2 })]],
      ['m-d', 'D', 'Clock Rope', '⏰', 'Use same-size pieces.', 'Compare rope lengths and clock parts.', 12, 8, ['Show one third hour.', 'Compare two ropes.', 'Build one whole bridge.'], [choice('md1', 'One third of an hour is?', '20 minutes', [['30 minutes', 'TIME_FRACTION_MISREAD'], ['15 minutes', 'TIME_FRACTION_MISREAD']], { parts: 3, shaded: 1 }), choice('md2', 'Which rope is longer?', '2/3 m', [['3/5 m', 'COMPARE_UNLIKE_GUESS'], ['Same', 'COUNT_PIECES_ONLY']], { parts: 15, shaded: 10 })]],
    ]),
    games: [rounds('Reef Twins', '🐚', [['Find a twin of one half.', '2/4', 4, 2, ['1/4', 'NO_EQUIVALENCE_IDEA'], ['3/4', 'NO_EQUIVALENCE_IDEA']], ['Shrink six eighths.', '3/4', 8, 6, ['6/8', 'NOT_SIMPLEST'], ['4/3', 'SWAP_NUM_DEN']]]), rounds('Reef Café', '🧁', [['Fill three quarters.', '3/4', 4, 3, ['2/4', 'WRONG_TOTAL'], ['1/4', 'ONLY_COUNT_ONE']], ['Fill five sixths.', '5/6', 6, 5, ['1/6', 'ONLY_COUNT_ONE'], ['6/5', 'SWAP_NUM_DEN']]]), rounds('Island Shop', '🏷️', [['Bag three fourths of twelve.', '9', 4, 3, ['3', 'OF_MEANS_ONE_PART'], ['12', 'NO_DISCOUNT_APPLIED']], ['One quarter off 20 coins. Pay?', '15', 4, 3, ['5', 'PAY_THE_DISCOUNT'], ['20', 'NO_DISCOUNT_APPLIED']]]), rounds('Bridge Builder', '🌉', [['Build one whole.', '1', 4, 4, ['1/2', 'STOPPED_AFTER_FIRST_STEP'], ['1/4', 'STOPPED_AFTER_FIRST_STEP']], ['What plank fills one quarter?', '1/4', 4, 1, ['1/2', 'WRONG_TOTAL'], ['1/3', 'WRONG_TOTAL']]])],
    boss: boss([['Twin of two thirds?', '4/6', 6, 4, ['3/4', 'EQUIV_ADD_NOT_MULT'], ['2/6', 'EQUIV_CHANGE_ONE_NUMBER']], ['Simplest form of six eighths?', '3/4', 8, 6, ['6/8', 'NOT_SIMPLEST'], ['4/3', 'SWAP_NUM_DEN']], ['One half plus one third?', '5/6', 6, 5, ['2/5', 'ADD_NUM_AND_DEN'], ['1', 'ESTIMATE_OFF']], ['Seven fourths is?', '1 3/4', 4, 3, ['3 1/4', 'IMPROPER_REMAINDER_MISUSE'], ['1 1/4', 'IMPROPER_REMAINDER_MISUSE']], ['Three fifths of 20?', '12', 5, 3, ['4', 'OF_MEANS_ONE_PART'], ['15', 'USED_WRONG_FRACTION']], ['24 coins, one third off. Pay?', '16', 3, 2, ['8', 'PAY_THE_DISCOUNT'], ['24', 'NO_DISCOUNT_APPLIED']], ['One third hour?', '20 minutes', 3, 1, ['30 minutes', 'TIME_FRACTION_MISREAD'], ['15 minutes', 'TIME_FRACTION_MISREAD']], ['Longer rope?', '3/4 m', 12, 9, ['2/3 m', 'COMPARE_UNLIKE_GUESS'], ['Same', 'COUNT_PIECES_ONLY']]]),
    explain: ['Check piece sizes.', 'Cut to the same size.', 'Add or compare.', 'Simplify the answer.'],
  },
  advanced: {
    wonder: { title: 'Summit Peak', tagline: 'Can you light the Observatory?', particles: ['🔭', '⭐', '🌙', '✨'], beats: [{ headline: 'Dividing makes it smaller…?', narration: 'Mei has three metres of ribbon. Each lantern needs one quarter metre.' }, { headline: 'Make your guess!', prompt: 'Will there be fewer, exactly, or more than three pieces?', narration: 'Will there be fewer, exactly, or more than three pieces?', go: 'Cut!' }, { headline: 'Twelve pieces!', narration: 'Dividing by a fraction made the answer bigger. Let us find out why.', cta: 'Start the Story' }] },
    story: [['The Garden on the Slope', 'Plant one half of three quarters of the garden. Half of a part? Let us slice the slice!', '🌿', 'Lab A · Slice of a Slice'], ['Ribbon for Lanterns', 'Each lantern needs one quarter metre. We have three metres. Count how many pieces fit.', '✂️', 'Lab B · How Many Fit'], ['Missing Coins', 'Mei spent one third, then half of the rest. A bar keeps track of every part.', '🪙', 'Lab C · Bar-Model Detective'], ['Lucky Spinner', 'Chance is a fraction: parts you want over all the equal parts.', '🎡', 'Lab D · Chance Lab']],
    labs: labs([
      ['a-a', 'A', 'Slice of a Slice', '🌿', 'A part of a part multiplies.', 'Colour an area inside another area.', 6, 3, ['Make one half of one half.', 'Make two thirds of three fourths.', 'Simplify six twelfths.'], [choice('aa1', 'What is two thirds of one half?', '1/3', [['2/6', 'NOT_SIMPLEST'], ['3/5', 'ADD_NUM_AND_DEN']], { parts: 6, shaded: 2 }), choice('aa2', 'Is one half of one third bigger or smaller?', 'Smaller', [['Bigger', 'MULT_ALWAYS_BIGGER'], ['Same', 'NO_SIZE_SENSE']], { parts: 6, shaded: 1 })]],
      ['a-b', 'B', 'How Many Fit?', '➗', 'Count how many pieces fit.', 'Cut ribbons into equal small pieces.', 8, 4, ['Cut two into thirds.', 'Cut three into quarters.', 'Find a leftover.'], [choice('ab1', 'Three divided by one quarter is?', '12', [['3/4', 'MULTIPLY_INSTEAD'], ['4', 'USED_DEN_ONLY']], { parts: 12, shaded: 12 }), choice('ab2', 'Three divided by one quarter is?', 'Bigger than three', [['Smaller', 'DIVIDE_ALWAYS_SMALLER'], ['The same', 'NO_SIZE_SENSE']], { parts: 12, shaded: 12 })]],
      ['a-c', 'C', 'Bar-Model Detective', '📊', 'Draw the whole. Track the rest.', 'Spend pieces from a bar, one step at a time.', 12, 8, ['Spend one third.', 'Spend half of the rest.', 'Work backwards once.'], [choice('ac1', 'One third then one fourth of whole. What is left?', '5/12', [['7/12', 'ANSWERED_THE_OPPOSITE'], ['1/12', 'SUBTRACTED_FRACTIONS']], { parts: 12, shaded: 5 }), choice('ac2', 'Half, then one fourth of rest: second spend?', '1/8', [['1/4', 'OF_THE_WHOLE_NOT_REST'], ['3/4', 'ADD_INSTEAD_OF_MULT']], { parts: 8, shaded: 1 })]],
      ['a-d', 'D', 'Chance Lab', '🎡', 'Chance is wanted over all.', 'Paint spinner sectors, then compare chances.', 12, 4, ['Make one quarter blue.', 'Make yellow impossible.', 'Make red certain.'], [choice('ad1', 'Three red, four blue, five green. Blue chance?', '1/3', [['4/12', 'NOT_SIMPLEST'], ['12/4', 'SWAP_NUM_DEN']], { parts: 12, shaded: 4 }), choice('ad2', 'Chance of not green?', '7/12', [['5/12', 'ANSWERED_THE_OPPOSITE'], ['12/7', 'SWAP_NUM_DEN']], { parts: 12, shaded: 7 })]],
    ]),
    games: [rounds('Summit Garden', '🌿', [['One half of one half?', '1/4', 4, 1, ['1/2', 'IGNORED_SECOND_FRACTION'], ['2/4', 'NOT_SIMPLEST']], ['Two thirds of three fourths?', '1/2', 12, 6, ['6/12', 'NOT_SIMPLEST'], ['5/7', 'ADD_NUM_AND_DEN']]]), rounds('Ribbon Cutter', '✂️', [['Two metres divided by one half?', '4', 4, 4, ['1/2', 'MULTIPLY_INSTEAD'], ['2', 'USED_DEN_ONLY']], ['Three metres divided by one quarter?', '12', 12, 12, ['3/4', 'MULTIPLY_INSTEAD'], ['4', 'USED_DEN_ONLY']]]), rounds('Detective Agency', '🕵️', [['24 coins: one third, then half rest. Left?', '8', 3, 1, ['16', 'STOPPED_AFTER_FIRST_STEP'], ['12', 'HALF_OF_WHOLE']], ['40 stickers: one fifth, then half rest. Left?', '16', 5, 2, ['32', 'STOPPED_AFTER_FIRST_STEP'], ['20', 'HALF_OF_WHOLE']]]), rounds('Spinner Studio', '🎡', [['Blue chance one quarter?', '2 blue of 8', 8, 2, ['4 blue of 8', 'WRONG_TOTAL'], ['1 blue of 8', 'ONLY_COUNT_ONE']], ['Green chance three fifths?', '6 green of 10', 10, 6, ['3 green of 10', 'ONLY_COUNT_ONE'], ['5 green of 10', 'WRONG_TOTAL']]])],
    boss: boss([['What is two thirds of three fourths?', '1/2', 12, 6, ['6/12', 'NOT_SIMPLEST'], ['5/7', 'ADD_NUM_AND_DEN']], ['What is three fifths of one half?', '3/10', 10, 3, ['3/5', 'IGNORED_SECOND_FRACTION'], ['11/10', 'ADD_INSTEAD_OF_MULT']], ['How many quarter scoops fill three cups?', '12', 12, 12, ['3/4', 'MULTIPLY_INSTEAD'], ['4', 'USED_DEN_ONLY']], ['Three fourths cut into eighths?', '6', 8, 6, ['3/32', 'MULTIPLY_INSTEAD'], ['8', 'USED_DEN_ONLY']], ['One third then one fourth. Fraction left?', '5/12', 12, 5, ['7/12', 'ANSWERED_THE_OPPOSITE'], ['1/12', 'SUBTRACTED_FRACTIONS']], ['Half then quarter of rest; six left. Start?', '16', 8, 3, ['8', 'UNDID_ONLY_ONE_STEP'], ['12', 'ADDED_BACK_FRACTIONS']], ['Spinner: not green?', '7/12', 12, 7, ['5/12', 'ANSWERED_THE_OPPOSITE'], ['12/7', 'SWAP_NUM_DEN']], ['Best fix?', 'Dividing by a fraction less than one can give more.', 4, 4, ['Dividing always makes less', 'DIVIDE_ALWAYS_SMALLER'], ['It is four thirds', 'FLIPPED_WRONG_PART']]]),
    explain: ['Draw the whole bar.', 'Split to match the fraction.', 'Mark what is used.', 'Find what is left.', 'Check that it makes sense.'],
  },
};
Object.assign(CONTENT.beginner.labs[0], LAB_A);
Object.assign(CONTENT.beginner.labs[1], LAB_B);
Object.assign(CONTENT.beginner.labs[2], LAB_C);
Object.assign(CONTENT.beginner.labs[3], LAB_D);
CONTENT.beginner.games[3] = CRAB_GAME;
CONTENT.beginner.games[1] = FISHING;
Object.assign(CONTENT.builder.labs[0], BUILDER_LABS.a);
Object.assign(CONTENT.builder.labs[1], BUILDER_LABS.b);
Object.assign(CONTENT.builder.labs[3], BUILDER_LABS.d);
Object.assign(CONTENT.advanced.labs[0], ADVANCED_LAB_A);
Object.assign(CONTENT.builder.labs[2], BUILDER_LAB_C);
Object.assign(CONTENT.advanced.labs[1], ADVANCED_LABS.b);
Object.assign(CONTENT.advanced.labs[2], ADVANCED_LABS.c);
Object.assign(CONTENT.advanced.labs[3], ADVANCED_LABS.d);
CONTENT.beginner.games[0] = PIZZA;
CONTENT.beginner.games[2] = HUNT;
CONTENT.builder.games[3] = BRIDGE;
CONTENT.builder.games[0] = G7.REEF_TWINS;
CONTENT.builder.games[1] = G7.REEF_CAFE;
CONTENT.builder.games[2] = G7.ISLAND_SHOP;
CONTENT.advanced.games[0] = G7.SUMMIT_GARDEN;
CONTENT.advanced.games[1] = G7.RIBBON_CUTTER;
CONTENT.advanced.games[2] = G7.DETECTIVE_AGENCY;
CONTENT.advanced.games[3] = G7.SPINNER_STUDIO;
