import React, { useEffect, useMemo, useReducer, useState } from 'react';
import { Volume2, VolumeX, Home, ChevronLeft, ChevronRight, LockKeyhole, Check, Sparkles, RotateCcw } from 'lucide-react';
import { frac, add, mul, toAria } from './core/fraction/index.js';
import { initialState } from './app/initialState.js';
import { reducer } from './app/reducer.js';
import { loadState, saveState } from './app/persistence.js';
import { levels, levelOrder } from './config/levels.js';
import { stories } from './content/story.js';
import { starsFor, unlockedLevels } from './utils/scoring.js';

const phaseNames = ['wonder', 'story', 'simulate', 'play', 'reflect'];
const fractionQuestions = {
  easy: [
    { prompt: 'A bar is cut into 6 equal parts. Five are shaded. What fraction is shaded?', n: 5, d: 6, options: [[5,6],[6,5],[1,6],[5,11]], tag: 'SWAP_NUM_DEN', visual: [6,5] },
    { prompt: 'Which fraction is greater?', compare: true, left: [3,8], right: [3,5], options: [[3,8],[3,5],[6,13],[1,2]], correct: 1, tag: 'BIG_DENOM_BIG_FRACTION' },
    { prompt: 'Which fraction is equivalent to one half?', options: [[1,2],[2,3],[3,8],[4,10]], correct: 0, tag: 'EQUIV_ADD_NOT_MULT' },
    { prompt: 'Two sevenths plus three sevenths equals…', options: [[5,7],[5,14],[6,7],[2,7]], correct: 0, tag: 'ADD_DENOMINATORS' },
  ],
  medium: [
    { prompt: 'Write twelve sixths in simplest form.', options: [[2,1],[6,12],[2,6],[1,2]], correct: 0, tag: 'SIMPLIFY_PARTIAL' },
    { prompt: 'Which is the mixed number for seventeen fifths?', options: ['3 and 2/5','2 and 3/5','3 and 5/2','4 and 1/5'], correct: 0, tag: 'IMPROPER_REMAINDER_MISUSE' },
    { prompt: 'Five sixths minus one half equals…', options: [[1,3],[2,6],[4,6],[1,2]], correct: 0, tag: 'ADD_NUM_KEEP_DEN_UNLIKE' },
    { prompt: 'Three quarters of 24 crabs are in the reef. How many crabs?', options: [18, 6, 8, 21], correct: 0, tag: 'OF_MEANS_ONE_PART' },
  ],
  hard: [
    { prompt: 'Two thirds times three quarters equals…', options: [[1,2],[6,7],[6,12],[5,12]], correct: 0, tag: 'MULT_ADD_CONFUSION' },
    { prompt: 'How many quarter-lengths fit inside 3 whole lengths?', options: [12, 3, 4, 7], correct: 0, tag: 'DIV_WHOLE_BY_FRACTION_SHRINKS' },
    { prompt: 'A fraction of a fraction is best shown first with a…', options: ['area model','number line','clock','tally mark'], correct: 0, tag: 'RANDOM_NEAR' },
    { prompt: 'Otto asks: “Is it in simplest form — and does the answer make sense?” This is his…', options: ['third question','first question','secret password','station rule'], correct: 0, tag: 'RANDOM_NEAR' },
  ],
};

function Frac({ n, d, size = '' }) { return <span className={`fraction ${size}`} role="img" aria-label={toAria({ n, d })}><span>{n}</span><span className="fraction-rule" /><span>{d}</span></span>; }
function formatOption(option) { if (Array.isArray(option)) return <Frac n={option[0]} d={option[1]} />; return option; }

export default function App() {
  const [state, dispatch] = useReducer(reducer, initialState, (fresh) => loadState() || fresh);
  useEffect(() => { saveState(state); }, [state]);
  const unlocked = unlockedLevels(state);
  const level = levels[state.level];
  const go = (phase) => dispatch({ type: 'SET_PHASE', phase });
  return <div className={`app ${state.calmMotion ? 'calm' : ''}`}>
    <Header state={state} level={level} go={go} dispatch={dispatch} />
    <main className="main">
      {state.phase === 'intro' && <Intro dispatch={dispatch} />}
      {state.phase === 'hub' && <Hub state={state} dispatch={dispatch} unlocked={unlocked} />}
      {state.phase === 'wonder' && <Wonder state={state} dispatch={dispatch} />}
      {state.phase === 'story' && <Story state={state} dispatch={dispatch} />}
      {state.phase === 'simulate' && <Simulate state={state} dispatch={dispatch} />}
      {state.phase === 'play' && <Play state={state} dispatch={dispatch} />}
      {state.phase === 'reflect' && <Reflect dispatch={dispatch} />}
      {state.phase === 'certificate' && <Certificate state={state} dispatch={dispatch} />}
    </main>
  </div>;
}

function Header({ state, level, go, dispatch }) {
  const active = state.phase === 'intro' || state.phase === 'certificate' ? '' : state.phase;
  return <header className="topbar">
    <button className="brand" onClick={() => go('hub')} aria-label="Go to island hub"><span className="brand-mark">⅓</span><span>Fraction Isles</span></button>
    <nav className="phase-nav" aria-label="Learning phases">{phaseNames.map((phase) => <button key={phase} className={`phase-pill ${active === phase ? 'active' : ''}`} onClick={() => phase !== 'reflect' || state.levels.hard.boss ? go(phase) : null}>{phase[0].toUpperCase() + phase.slice(1)}</button>)}</nav>
    <div className="top-actions"><span className="level-chip">{level.icon} {level.label}</span><div className="stats"><span className="stat-chip">✨ {state.scoring.xp} XP</span><span className="stat-chip">🔥 {state.scoring.streak}</span></div><button className="icon-button" onClick={() => dispatch({ type: 'TOGGLE_AUDIO' })} aria-label={state.audioEnabled ? 'Turn audio off' : 'Turn audio on'}>{state.audioEnabled ? <Volume2 size={19} /> : <VolumeX size={19} />}</button></div>
  </header>;
}

function Intro({ dispatch }) { const [nickname, setNickname] = useState(''); return <section className="hero screen"><div className="hero-copy"><div className="eyebrow">A fraction adventure for curious builders</div><h1>Rebuild the isles, one piece at a time.</h1><p>A storm has scattered the Fraction Isles. Share fairly, measure carefully, and help Mei, Danish, and Otto restore three bright islands.</p><div className="cta-row"><input className="nickname" value={nickname} onChange={(e) => setNickname(e.target.value)} maxLength={12} placeholder="Your name (optional)" aria-label="Your name" /><button className="primary" onClick={() => dispatch({ type: 'START', nickname })}>Set sail <ChevronRight size={19} /></button></div><p className="muted">No account needed · your progress stays on this device.</p></div><div className="island-illustration" aria-label="A cheerful tropical island illustration" role="img">🏝️</div></section>; }

function Hub({ state, dispatch, unlocked }) { return <section className="screen"><div className="section-heading"><div><div className="eyebrow">Archipelago hub</div><h2>Choose your next island</h2></div><button className="secondary" onClick={() => dispatch({ type: 'NEW_GAME' })}><RotateCcw size={17} /> New game</button></div><div className="island-grid">{levelOrder.map((id) => { const item = levels[id]; const p = state.levels[id]; const canEnter = unlocked[id]; const progress = Math.round((p.stations.filter(Boolean).length + p.stars) / 7 * 100); return <article className={`card island-card ${canEnter ? '' : 'locked'}`} key={id}><div><div className="island-icon">{item.icon}</div><div className="eyebrow">{item.label}</div><h3>{item.name}</h3><p>{canEnter ? item.description : 'Restore the island before this one opens.'}</p></div><div><div className="progress-track"><div className="progress-fill" style={{ width: `${canEnter ? progress : 0}%` }} /></div><button className={canEnter ? 'primary' : 'secondary'} disabled={!canEnter} onClick={() => { dispatch({ type: 'SET_LEVEL', level: id }); dispatch({ type: 'SET_PHASE', phase: p.storyPanel > 0 ? 'simulate' : 'story' }); }}>{canEnter ? 'Enter island' : <><LockKeyhole size={16} /> Locked</>}</button></div></article>; })}</div></section>; }

function Wonder({ state, dispatch }) { const beats = [{ title: 'A fair share', body: 'Imagine a coconut bar split for four friends. What would make the sharing fair?', icon: '🥥' }, { title: 'A careful eye', body: 'Look for equal-sized pieces before naming a fraction. Otto will ask this often.', icon: '👁️' }, { title: 'Your builder badge', body: 'You are ready to measure, model, and explain. The first island is waiting.', icon: '🧭' }]; const beat = beats[state.wonderStep]; return <section className="card screen" style={{ maxWidth: 760, margin: '40px auto' }}><div className="eyebrow">Wonder · {state.wonderStep + 1} of 3</div><div style={{ fontSize: 86, margin: '20px 0' }}>{beat.icon}</div><h2>{beat.title}</h2><p style={{ fontSize: 22 }}>{beat.body}</p><div className="cta-row"><button className="primary" onClick={() => dispatch({ type: 'WONDER_NEXT', done: state.wonderStep === 2 })}>{state.wonderStep === 2 ? 'Visit Sunrise Shore' : 'I’m ready'} <ChevronRight size={19} /></button></div></section>; }

function Story({ state, dispatch }) { const story = stories[state.level]; const p = state.levels[state.level]; const panel = story.panels[p.storyPanel]; return <section className="screen"><div className="section-heading"><div><div className="eyebrow">Story · {levelOrder.indexOf(state.level) + 1} of 3</div><h2>{story.title}</h2></div><span className="level-chip">{levels[state.level].icon} {levels[state.level].name}</span></div><div className="story-layout"><div className="story-art" role="img" aria-label={panel.title}>{panel.art}</div><article className="card story-copy"><div className="eyebrow">{panel.kicker}</div><h2>{panel.title}</h2><p style={{ fontSize: 22 }}>{panel.body}</p><div className="card" style={{ background: '#fff8ea', boxShadow: 'none' }}><strong>Otto’s idea</strong><p style={{ marginBottom: 0 }}>{panel.idea}</p></div><div className="story-dots" aria-label={`Panel ${p.storyPanel + 1} of 3`}>{story.panels.map((_, i) => <span key={i} className={`dot ${i === p.storyPanel ? 'active' : ''}`} />)}</div><div className="cta-row"><button className="secondary" disabled={p.storyPanel === 0} onClick={() => dispatch({ type: 'STORY_PREV' })}><ChevronLeft size={18} /> Back</button><button className="primary" onClick={() => dispatch({ type: 'STORY_NEXT', last: p.storyPanel === 2 })}>{p.storyPanel === 2 ? 'Open stations' : 'Next panel'} <ChevronRight size={18} /></button></div></article></div></section>; }

function Simulate({ state, dispatch }) { const p = state.levels[state.level]; const stations = [{ title: 'Equal parts', icon: '🪵', body: 'Tap complete after checking that every part is the same size.' }, { title: 'Fraction wall', icon: '🧱', body: 'Match fractions that cover the same length.' }, { title: 'Supply share', icon: '⛵', body: 'Share a set into equal groups.' }, { title: 'Oops Desk', icon: '🔍', body: 'Find the mistake and explain why it is not fair.' }]; return <section className="screen"><div className="section-heading"><div><div className="eyebrow">Simulate · build before you calculate</div><h2>Try the island stations</h2><p>Each station awards 25 XP. Use Otto’s questions as your checklist.</p></div><div className="level-chip">{p.stations.filter(Boolean).length} / 4 complete</div></div><div className="station-grid">{stations.map((station, index) => <article className={`card station ${p.stations[index] ? 'done' : ''}`} key={station.title}><div><div className="station-number">{p.stations[index] ? <Check size={20} /> : index + 1}</div><div style={{ fontSize: 46, margin: '16px 0 8px' }}>{station.icon}</div><h3>{station.title}</h3><p>{station.body}</p></div><button className={p.stations[index] ? 'secondary' : 'primary'} onClick={() => dispatch({ type: 'STATION_COMPLETE', station: index, allDone: p.stations.every((done, i) => done || i === index) })}>{p.stations[index] ? 'Completed' : 'Complete station'}</button></article>)}</div>{p.stations.every(Boolean) && <div className="card" style={{ marginTop: 20, background: '#e8fff4' }}><h3>All stations ready!</h3><p>You have built the concrete ideas. Now practise choosing the right fraction tool.</p><button className="primary" onClick={() => dispatch({ type: 'SET_PHASE', phase: 'play' })}>Start practice <ChevronRight size={18} /></button></div>}</section>; }

function Play({ state, dispatch }) { const p = state.levels[state.level]; const questions = fractionQuestions[state.level]; const index = p.questions.findIndex((_, i) => !p.questions[i]); const qIndex = index === -1 ? questions.length : index; if (qIndex >= questions.length) return <LevelComplete state={state} dispatch={dispatch} />; return <Question key={qIndex} state={state} dispatch={dispatch} q={questions[qIndex]} index={qIndex} total={questions.length} />; }

function Question({ state, dispatch, q, index, total }) { const [picked, setPicked] = useState(null); const [submitted, setSubmitted] = useState(false); const correctIndex = q.correct ?? (q.options.findIndex((option) => Array.isArray(option) && option[0] === q.n && option[1] === q.d)); const correct = picked === correctIndex; const submit = () => { if (picked !== null) setSubmitted(true); }; const next = () => dispatch({ type: 'ANSWER', index, correct, tag: q.tag }); return <section className="screen"><div className="section-heading"><div><div className="eyebrow">Play · question {index + 1} of {total}</div><h2>Choose the right tool</h2></div><span className="level-chip">{state.levels[state.level].answers.filter((answer) => answer.correct).length} correct</span></div><div className="practice-layout"><aside className="card"><div className="eyebrow">Otto’s three questions</div><h3>Before you answer…</h3><ol style={{ paddingLeft: 22, color: 'var(--ink-600)', lineHeight: 1.8 }}><li>Are the pieces equal?</li><li>Are the pieces the same size?</li><li>Is it simplest, and does it make sense?</li></ol><div className="model-bar" aria-label="Fraction model">{q.visual && Array.from({ length: q.visual[0] }, (_, i) => <span className={`model-part ${i < q.visual[1] ? 'shaded' : ''}`} key={i} />)}</div></aside><article className="card question-card"><div className="eyebrow">{state.level === 'easy' ? 'SHARE FAIRLY' : state.level === 'medium' ? 'MAKE IT FIT' : 'EXPLAIN THE MODEL'}</div><h3 style={{ fontSize: 30, lineHeight: 1.3 }}>{q.prompt}</h3>{q.compare && <p style={{ fontSize: 28 }}><Frac n={q.left[0]} d={q.left[1]} /> or <Frac n={q.right[0]} d={q.right[1]} />?</p>}<div className="answer-options">{q.options.map((option, optionIndex) => <button key={optionIndex} disabled={submitted} className="answer-option" onClick={() => setPicked(optionIndex)} style={picked === optionIndex ? { borderColor: 'var(--coral-500)', background: '#fff0ed' } : {}}>{formatOption(option)}</button>)}</div>{submitted && <div className={`feedback ${correct ? '' : 'wrong'}`}>{correct ? <><Sparkles size={18} /> Yes! You checked the pieces before choosing.</> : <>Good try. Otto says: {q.tag === 'SWAP_NUM_DEN' ? 'the top counts selected parts and the bottom counts all equal parts.' : 'draw or count the equal parts before committing.'}</>}</div>}<div className="cta-row"><button className="primary" onClick={submit} disabled={picked === null || submitted}>{submitted ? <><Check size={18} /> Answer checked</> : 'Check answer'}</button>{submitted && <button className="secondary" onClick={next}>Next question <ChevronRight size={18} /></button>}</div></article></div></section>; }

function LevelComplete({ state, dispatch }) { const p = state.levels[state.level]; const correct = p.answers.filter((answer) => answer.correct).length; const stars = starsFor(correct, p.questions.length); const next = state.level === 'easy' ? 'medium' : state.level === 'medium' ? 'hard' : null; return <section className="card screen" style={{ maxWidth: 760, margin: '30px auto', textAlign: 'center' }}><div style={{ fontSize: 76 }}>🏝️</div><div className="eyebrow">Island restored</div><h2>{levels[state.level].name} is glowing again</h2><p>You checked the pieces, explained your choices, and earned {correct} out of {p.questions.length} practice stars.</p><div style={{ fontSize: 46, letterSpacing: 8, margin: '20px 0' }}>{'★'.repeat(stars)}<span style={{ color: 'var(--sand-200)' }}>{'★'.repeat(3 - stars)}</span></div><button className="primary" onClick={() => dispatch({ type: 'LEVEL_COMPLETE', stars, nextLevel: next })}>{next ? `Sail to ${levels[next].name}` : 'Open Reflect'} <ChevronRight size={18} /></button></section>; }

function Reflect({ dispatch }) { const [choice, setChoice] = useState(null); const [journal, setJournal] = useState(''); return <section className="reflection card screen"><div className="eyebrow">Reflect · your builder log</div><h2>What will you remember?</h2><p>Otto’s final question: which habit will help you catch a fraction mistake next time?</p><div className="reflection-row">{['Equal parts','Same size','Simplest form','Draw a model','All three'].map((label, i) => <button className={`reflection-choice ${choice === i ? 'selected' : ''}`} onClick={() => setChoice(i)} key={label} aria-label={label}>{['🧩','📏','✨','✏️','🦦'][i]}</button>)}</div><label htmlFor="journal"><strong>One thing I can explain now:</strong></label><textarea id="journal" value={journal} onChange={(e) => setJournal(e.target.value.slice(0, 300))} rows="4" style={{ display: 'block', width: '100%', marginTop: 10, border: '2px solid var(--sand-200)', borderRadius: 14, padding: 14, resize: 'vertical' }} placeholder="Write a short note to your future self…" /><div className="cta-row"><button className="primary" disabled={choice === null} onClick={() => dispatch({ type: 'REFLECT_DONE' })}>Finish my log <Check size={18} /></button></div></section>; }

function Certificate({ state, dispatch }) { return <section className="certificate card screen"><div className="eyebrow">Fraction Isles · Island Architect</div><div className="certificate-seal">🏆</div><h2>Certificate of careful sharing</h2><p>{state.nickname ? `${state.nickname}, ` : ''}you travelled across Sunrise Shore, Tidepool Reef, and Summit Peak. You practised equal parts, equivalent fractions, operations, and bar models.</p><h3>“Before you answer, check the pieces.”</h3><p className="muted">Fraction Isles · completed on this device</p><div className="cta-row" style={{ justifyContent: 'center' }}><button className="secondary" onClick={() => dispatch({ type: 'SET_PHASE', phase: 'hub' })}><Home size={18} /> Back to hub</button><button className="primary" onClick={() => window.print()}>Print certificate</button></div></section>; }
