import React, { useEffect, useMemo, useReducer, useState } from 'react';
import { Check, ChevronLeft, ChevronRight, Home as HomeIcon, LockKeyhole, Map, Play, RotateCcw, Settings, Sparkles, Volume2, VolumeX, X } from 'lucide-react';
import { LEVELS, LEVEL_ORDER } from './config/levels.js';
import { makeInitialState } from './app/initialState.js';
import { reducer } from './app/reducer.js';
import { loadState, saveState } from './app/persistence.js';
import { allLevelsDone, levelProgress, levelUnlocked, nextNodeIndex, nodeStatus, totalStars, trailOf } from './app/selectors.js';
import { LESSONS } from './content/lessons/index.js';
import { GAMES } from './content/games/index.js';
import { BOSS } from './content/boss/index.js';

const hashFor = (route) => {
  if (route.screen === 'home') return '#/';
  if (route.screen === 'trail') return `#/level/${route.level}`;
  if (route.screen === 'lesson') return `#/level/${route.level}/learn/${route.index + 1}`;
  if (route.screen === 'game') return `#/level/${route.level}/play/${route.index + 1}`;
  if (route.screen === 'boss') return `#/level/${route.level}/boss`;
  if (route.screen === 'levelDone') return `#/done/${route.level}`;
  return '#/certificate';
};

const go = (dispatch, route) => dispatch({ type: 'GO', route });

const renderFraction = (value) => {
  if (!Array.isArray(value)) return value;
  return <span className="frac-option" aria-label={`${value[0]} over ${value[1]}`}><span>{value[0]}</span><i /><span>{value[1]}</span></span>;
};

export default function App() {
  const [state, dispatch] = useReducer(reducer, undefined, () => loadState() || makeInitialState());
  useEffect(() => { saveState(state); window.history.replaceState(null, '', hashFor(state.route)); }, [state]);
  useEffect(() => { const onHash = () => { if (window.location.hash === '#/' || !window.location.hash) go(dispatch, { screen: 'home' }); }; window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  return <div className={`app ${state.settings.calmMotion ? 'calm' : ''}`}><TopBar state={state} dispatch={dispatch} /><main className="redesign-main"><RouteView state={state} dispatch={dispatch} /></main></div>;
}

function TopBar({ state, dispatch }) {
  const [settingsOpen, setSettingsOpen] = useState(false);
  const route = state.route;
  const cfg = route.level ? LEVELS[route.level] : null;
  const routeTitle = route.screen === 'trail' ? `${cfg?.label} Trail` : route.screen === 'lesson' ? LESSONS[route.level]?.[route.index]?.title : route.screen === 'game' ? GAMES[route.level]?.[route.index]?.title : route.screen === 'boss' ? 'Boss Challenge' : route.screen === 'levelDone' ? 'Level Complete' : route.screen === 'certificate' ? 'Certificate' : '';
  return <><header className="redesign-topbar"><button className="brand redesign-brand" onClick={() => go(dispatch, { screen: 'home' })} aria-label="Go to home"><span className="brand-mark">⅓</span><span>Fraction Isles</span></button>{route.screen !== 'home' && <div className="breadcrumb"><button onClick={() => go(dispatch, { screen: 'home' })}><Map size={16} /> Map</button><span>›</span><strong>{routeTitle}</strong></div>}<div className="redesign-stats"><span className="stat-chip">⭐ {totalStars(state)}</span><span className="stat-chip">✨ {state.scoring.xp}</span><button className="icon-button" onClick={() => dispatch({ type: 'TOGGLE_SETTING', key: 'audio' })} aria-label={state.settings.audio ? 'Turn audio off' : 'Turn audio on'}>{state.settings.audio ? <Volume2 size={19} /> : <VolumeX size={19} />}</button><button className="icon-button" onClick={() => setSettingsOpen(true)} aria-label="Open settings"><Settings size={19} /></button></div></header>{settingsOpen && <SettingsPanel state={state} dispatch={dispatch} close={() => setSettingsOpen(false)} />}</>;
}

function SettingsPanel({ state, dispatch, close }) { const [confirm, setConfirm] = useState(false); return <div className="modal-backdrop" role="presentation"><section className="settings-panel card" role="dialog" aria-modal="true" aria-label="Grown-ups settings"><button className="modal-close" onClick={close} aria-label="Close settings"><X /></button><div className="eyebrow">Grown-ups</div><h2>Settings</h2><label className="setting-row"><span>Calm motion</span><button className={`toggle ${state.settings.calmMotion ? 'on' : ''}`} onClick={() => dispatch({ type: 'TOGGLE_SETTING', key: 'calmMotion' })}>{state.settings.calmMotion ? 'On' : 'Off'}</button></label><label className="setting-row"><span>Unlock all levels</span><button className={`toggle ${state.settings.unlockAll ? 'on' : ''}`} onClick={() => dispatch({ type: 'TOGGLE_SETTING', key: 'unlockAll' })}>{state.settings.unlockAll ? 'On' : 'Off'}</button></label><label className="setting-row"><span>Audio</span><button className={`toggle ${state.settings.audio ? 'on' : ''}`} onClick={() => dispatch({ type: 'TOGGLE_SETTING', key: 'audio' })}>{state.settings.audio ? 'On' : 'Off'}</button></label><div className="settings-danger">{confirm ? <><p>Reset all islands and stickers?</p><button className="secondary" onClick={() => { dispatch({ type: 'RESET' }); close(); }}>Yes, reset</button><button className="secondary" onClick={() => setConfirm(false)}>Keep progress</button></> : <button className="secondary" onClick={() => setConfirm(true)}><RotateCcw size={16} /> Reset progress</button>}</div></section></div>; }

function RouteView({ state, dispatch }) {
  switch (state.route.screen) {
    case 'trail': return <Trail state={state} dispatch={dispatch} level={state.route.level} />;
    case 'lesson': return <LessonPlayer state={state} dispatch={dispatch} level={state.route.level} index={state.route.index} />;
    case 'game': return <GameHost state={state} dispatch={dispatch} level={state.route.level} index={state.route.index} />;
    case 'boss': return <Boss state={state} dispatch={dispatch} level={state.route.level} />;
    case 'levelDone': return <LevelDone state={state} dispatch={dispatch} level={state.route.level} />;
    case 'certificate': return <Certificate state={state} dispatch={dispatch} />;
    default: return <Home state={state} dispatch={dispatch} />;
  }
}

function Home({ state, dispatch }) {
  const [name, setName] = useState(state.nickname);
  const [nameSaved, setNameSaved] = useState(Boolean(state.nickname));
  const unlocked = LEVEL_ORDER.filter((id) => levelUnlocked(state, id));
  const continueLevel = unlocked[unlocked.length - 1] || 'beginner';
  const continueIndex = nextNodeIndex(state, continueLevel);
  const trail = trailOf(continueLevel); const next = trail[continueIndex];
  const nextLabel = next?.kind === 'boss' ? 'Boss Challenge' : `${next?.kind === 'lesson' ? 'Learn' : 'Play'} ${next.index + 1} · ${next?.kind === 'lesson' ? LESSONS[continueLevel][next.index].title : GAMES[continueLevel][next.index].title}`;
  const saveName = () => { dispatch({ type: 'SET_NAME', name }); setNameSaved(true); };
  return <section className="redesign-screen home-screen"><div className="welcome-strip card"><div className="otto-welcome">🦦</div><div className="welcome-copy"><div className="eyebrow">Fraction Isles</div><h2>{state.nickname ? `Hi ${state.nickname}! Ready to rebuild?` : 'Hi! I’m Otto. Pick an island to start.'}</h2>{!nameSaved && <div className="name-row"><input className="nickname" value={name} onChange={(e) => setName(e.target.value)} maxLength={12} placeholder="Your name (optional)" aria-label="Your name" /><button className="secondary" onClick={saveName}>Save</button></div>}</div><button className="continue-card" onClick={() => go(dispatch, next?.kind === 'lesson' ? { screen: 'lesson', level: continueLevel, index: next.index } : next?.kind === 'game' ? { screen: 'game', level: continueLevel, index: next.index } : { screen: 'boss', level: continueLevel })}><Play size={20} fill="currentColor" /><span><b>Continue</b><small>{allLevelsDone(state) ? 'Play again' : nextLabel}</small></span></button></div><div className="map-heading"><div><div className="eyebrow">Your level map</div><h1>Learn a little. Play a little. Beat the Boss.</h1></div><p>Three islands. Short visual lessons. Twelve mini-games.</p></div><div className="level-map">{LEVEL_ORDER.map((id, index) => <LevelCard key={id} state={state} dispatch={dispatch} levelId={id} position={index} />)}</div><div className="home-footer card"><span>📒 Sticker book <b>{LEVEL_ORDER.reduce((n, id) => n + state.levels[id].lessons.filter(Boolean).length + state.levels[id].games.filter((game) => game.done).length + (state.levels[id].boss.done ? 1 : 0), 0)} / 27</b></span><span>✨ Short lessons · visual games · no timers</span></div></section>;
}

function LevelCard({ state, dispatch, levelId, position }) {
  const cfg = LEVELS[levelId]; const p = state.levels[levelId]; const unlocked = levelUnlocked(state, levelId); const progress = levelProgress(state, levelId); const lessons = LESSONS[levelId]; const stateClass = progress.pct === 0 ? 'faded' : progress.pct === 100 ? 'glowing' : 'growing';
  return <article className={`level-map-card card ${unlocked ? '' : 'locked'} ${stateClass}`}><div className="level-card-header"><span className="island-label">{cfg.island}</span><span className={`level-grade ${cfg.accent}`}>{cfg.grades}</span></div><div className="island-art" aria-label={`${cfg.island} illustration`} role="img"><span>{cfg.icon}</span><i>{position === 0 ? '🌴' : position === 1 ? '🐚' : '🏔️'}</i></div><div className="level-card-body"><div className="level-label-row"><div><div className="eyebrow">{cfg.label}</div><h2>{cfg.tagline}</h2></div><span className={`stage-badge stage-${levelId}`}>{cfg.stage}</span></div><div className="sticker-row" aria-label="Level contents">{lessons.map((lesson, i) => <span key={lesson.id} className={p.lessons[i] ? 'earned' : ''} title={lesson.title}>{lesson.sticker}</span>)}</div><div className="level-meta"><span>4 lessons</span><span>4 games</span><span>1 boss</span></div><div className="progress-line"><span style={{ width: `${unlocked ? progress.pct : 0}%` }} /></div><div className="level-progress-text">{unlocked ? `${progress.done} of ${progress.total} stops` : `🔒 Beat ${LEVELS[LEVEL_ORDER[Math.max(0, LEVEL_ORDER.indexOf(levelId) - 1)]]?.label || 'the previous level'} to open`}</div><button className={unlocked ? 'primary' : 'secondary'} disabled={!unlocked} onClick={() => go(dispatch, { screen: 'trail', level: levelId })}>{unlocked ? progress.done === 0 ? 'Start' : progress.pct === 100 ? 'Play again' : 'Continue' : <><LockKeyhole size={16} /> Locked</>}</button></div></article>;
}

function Trail({ state, dispatch, level }) {
  const cfg = LEVELS[level]; const nodes = trailOf(level); const [message, setMessage] = useState('');
  const openNode = (node, index) => { const status = nodeStatus(state, level, index); if (status === 'locked') { setMessage('Finish the step before this one first.'); return; } if (node.kind === 'lesson') go(dispatch, { screen: 'lesson', level, index: node.index }); else if (node.kind === 'game') go(dispatch, { screen: 'game', level, index: node.index }); else go(dispatch, { screen: 'boss', level }); };
  const next = nextNodeIndex(state, level);
  return <section className="redesign-screen trail-screen"><div className="trail-heading"><button className="back-link" onClick={() => go(dispatch, { screen: 'home' })}><ChevronLeft size={18} /> Map</button><div><div className="eyebrow">{cfg.label} · {cfg.grades}</div><h1>{cfg.island}</h1><p>{cfg.tagline}</p></div><div className="trail-stars">⭐ {state.levels[level].games.reduce((n, game) => n + game.stars, 0) + state.levels[level].boss.stars} / 15</div></div><div className="trail-path">{nodes.map((node, index) => { const status = nodeStatus(state, level, index); const content = node.kind === 'lesson' ? LESSONS[level][node.index] : node.kind === 'game' ? GAMES[level][node.index] : { title: 'Boss Challenge', sticker: '🏆', icon: '🏆' }; return <button key={`${node.kind}-${node.index}`} className={`trail-node ${status} ${index === next ? 'next' : ''}`} onClick={() => openNode(node, index)}><span className="trail-node-icon">{status === 'done' ? <Check size={24} /> : content.sticker || content.icon}</span><small>{node.kind === 'lesson' ? `Learn ${node.index + 1}` : node.kind === 'game' ? `Play ${node.index + 1}` : 'Boss'}</small><b>{content.title}</b>{(node.kind === 'game' || node.kind === 'boss') && status === 'done' && <em>★</em>}</button>; })}</div>{message && <div className="otto-toast" role="status">🦦 {message}</div>}<div className="learn-strip card"><div><div className="eyebrow">What you’ll learn</div><h3>{cfg.tagline}</h3></div><div className="remember-list">{LESSONS[level].map((lesson, index) => <span className={state.levels[level].lessons[index] ? 'revealed' : ''} key={lesson.id}>{state.levels[level].lessons[index] ? lesson.remember : '•••'}</span>)}</div></div><button className="primary trail-continue" onClick={() => openNode(nodes[next], next)}><Play size={18} fill="currentColor" /> Continue</button></section>;
}

function LessonPlayer({ state, dispatch, level, index }) {
  const lesson = LESSONS[level][index]; const [cardIndex, setCardIndex] = useState(0); const [selected, setSelected] = useState(null); const [checked, setChecked] = useState(false); const [complete, setComplete] = useState(false); const card = lesson.cards[cardIndex]; const isCorrect = selected === card.correct; const canNext = card.kind === 'see' || (selected !== null && (!checked || isCorrect));
  const next = () => { if (!canNext) return; if (cardIndex < lesson.cards.length - 1) { setCardIndex(cardIndex + 1); setSelected(null); setChecked(false); } else { dispatch({ type: 'LESSON_COMPLETE', level, index }); setComplete(true); } };
  if (complete) return <CompletionCard state={state} dispatch={dispatch} level={level} index={index} type="lesson" title={lesson.title} sticker={lesson.sticker} remember={lesson.remember} />;
  return <section className="redesign-screen player-screen"><button className="close-link" onClick={() => go(dispatch, { screen: 'trail', level })}><X size={18} /> Exit</button><div className="player-progress"><span className="eyebrow">{lesson.hook}</span><div className="dots-label">{lesson.cards.map((_, i) => <span key={i} className={i <= cardIndex ? 'active' : ''} />)} <b>{['See', 'Try', 'Check'][cardIndex]}</b></div></div><div className="lesson-stage card"><VisualStage kind={card.visual} calm={state.settings.calmMotion} /><div className="otto-bubble">🦦 <span>{card.kind === 'see' ? card.caption : card.kind === 'try' ? lesson.otto : card.explain}</span></div><div className="lesson-content"><div className="eyebrow">{card.kind === 'see' ? 'Look' : card.kind === 'try' ? 'Try it' : 'Check'}</div>{card.prompt && <h2>{card.prompt}</h2>}{card.options && <Options options={card.options} selected={selected} disabled={checked} onSelect={(i) => { setSelected(i); setChecked(false); }} />}{checked && !isCorrect && <div className="gentle-feedback">Not yet. Look at the picture again.</div>}</div><div className="player-actions">{card.kind !== 'see' && <button className="secondary" onClick={() => { setSelected(null); setChecked(false); }}>Reset</button>}{card.kind !== 'see' && !checked && <button className="secondary" disabled={selected === null} onClick={() => setChecked(true)}>Check</button>}<button className="primary" disabled={!canNext} onClick={next}>{cardIndex === lesson.cards.length - 1 ? 'Finish lesson' : 'Next'} <ChevronRight size={18} /></button></div></div></section>;
}

function GameHost({ state, dispatch, level, index }) {
  const game = GAMES[level][index]; const [roundIndex, setRoundIndex] = useState(0); const [selected, setSelected] = useState(null); const [submitted, setSubmitted] = useState(false); const [correctCount, setCorrectCount] = useState(0); const [finished, setFinished] = useState(false); const round = game.rounds[roundIndex]; const correct = selected === round.correct;
  const next = () => { if (!submitted) return; const count = correctCount + (correct ? 1 : 0); if (roundIndex === game.rounds.length - 1) { dispatch({ type: 'GAME_COMPLETE', level, index, correct: count, total: game.rounds.length }); setCorrectCount(count); setFinished(true); } else { setCorrectCount(count); setRoundIndex(roundIndex + 1); setSelected(null); setSubmitted(false); } };
  if (finished) return <CompletionCard state={state} dispatch={dispatch} level={level} index={index} type="game" title={game.title} sticker={game.icon} remember={`You finished ${game.title}.`} correct={correctCount} total={game.rounds.length} />;
  return <section className="redesign-screen player-screen"><button className="close-link" onClick={() => go(dispatch, { screen: 'trail', level })}><X size={18} /> Exit</button><div className="game-header"><div><div className="eyebrow">{game.icon} {game.title}</div><h1>Play it</h1></div><div className="round-dots">{game.rounds.map((_, i) => <span className={i <= roundIndex ? 'active' : ''} key={i} />)}<small>round {roundIndex + 1} of {game.rounds.length}</small></div></div><div className="game-stage card"><VisualStage kind={round.visual} calm={state.settings.calmMotion} /><div className="otto-bubble">🦦 <span>{game.intro}</span></div><h2>{round.prompt}</h2><Options options={round.options} selected={selected} disabled={submitted} onSelect={setSelected} /><div className="game-feedback">{submitted ? <span className={correct ? 'good' : 'gentle-feedback'}>{correct ? `Yes! ${round.explain}` : `Look again. ${round.explain}`}</span> : <span>Choose a card. There is no timer.</span>}</div><div className="player-actions"><button className="secondary" onClick={() => alert(game.intro)}>❓ How to play</button>{!submitted ? <button className="primary" disabled={selected === null} onClick={() => setSubmitted(true)}>Check</button> : <button className="primary" onClick={next}>{roundIndex === game.rounds.length - 1 ? 'Finish game' : 'Next'} <ChevronRight size={18} /></button>}</div></div></section>;
}

function Boss({ state, dispatch, level }) {
  const questions = BOSS[level]; const cfg = LEVELS[level]; const [index, setIndex] = useState(0); const [selected, setSelected] = useState(null); const [submitted, setSubmitted] = useState(false); const [score, setScore] = useState(0); const [finished, setFinished] = useState(false); const q = questions[index]; const correct = selected === q.correct;
  const next = () => { if (!submitted) return; const result = score + (correct ? 1 : 0); if (index === questions.length - 1) { dispatch({ type: 'BOSS_COMPLETE', level, correct: result, total: questions.length }); setScore(result); setFinished(true); } else { setScore(result); setIndex(index + 1); setSelected(null); setSubmitted(false); } };
  if (finished) return <BossResult state={state} dispatch={dispatch} level={level} score={score} total={questions.length} />;
  return <section className="redesign-screen player-screen"><button className="close-link" onClick={() => go(dispatch, { screen: 'trail', level })}><X size={18} /> Exit</button><div className="game-header"><div><div className="eyebrow">🏆 Boss Challenge · {cfg.island}</div><h1>Rebuild the {level === 'beginner' ? 'dock' : level === 'builder' ? 'reef bridge' : 'summit stairs'}</h1></div><div className="round-dots">{questions.map((_, i) => <span className={i <= index ? 'active' : ''} key={i} />)}<small>{index + 1} / {questions.length}</small></div></div><div className="boss-progress"><span style={{ width: `${((index + 1) / questions.length) * 100}%` }} /></div><div className="game-stage card boss-stage"><VisualStage kind={q.visual} calm={state.settings.calmMotion} /><h2>{q.prompt}</h2><Options options={q.options} selected={selected} disabled={submitted} onSelect={setSelected} /><div className="game-feedback">{submitted ? <span className={correct ? 'good' : 'gentle-feedback'}>{correct ? `Golden plank! ${q.explain}` : `The bridge still grows. ${q.explain}`}</span> : <span>Every answer adds a plank. Take your best look.</span>}</div><div className="player-actions">{!submitted ? <button className="primary" disabled={selected === null} onClick={() => setSubmitted(true)}>Add plank</button> : <button className="primary" onClick={next}>{index === questions.length - 1 ? 'Finish boss' : 'Next'} <ChevronRight size={18} /></button>}</div></div></section>;
}

function CompletionCard({ state, dispatch, level, index, type, title, sticker, remember, correct, total }) { return <section className="completion-card card redesign-screen"><div className="completion-sticker">{sticker}</div><div className="eyebrow">{type === 'lesson' ? 'Lesson complete' : 'Game complete'}</div><h1>{title}</h1><p>{remember}</p>{total && <div className="result-score">{correct} / {total} first tries</div>}<div className="star-burst">✨ ⭐ ✨</div><div className="player-actions"><button className="secondary" onClick={() => go(dispatch, { screen: 'trail', level })}>Back to trail</button>{type === 'lesson' ? <button className="primary" onClick={() => go(dispatch, { screen: 'game', level, index })}>Play it! <Play size={18} fill="currentColor" /></button> : <button className="primary" onClick={() => go(dispatch, { screen: 'trail', level })}>Next stop <ChevronRight size={18} /></button>}</div></section>; }

function BossResult({ state, dispatch, level, score, total }) { const cfg = LEVELS[level]; const passed = score >= cfg.passMark; return <section className="completion-card card redesign-screen"><div className="completion-sticker">{passed ? '🏆' : '🛠️'}</div><div className="eyebrow">{passed ? 'Boss complete' : 'Keep building'}</div><h1>{passed ? `${cfg.island} restored!` : 'Almost there!'}</h1><p>You got {score} of {total}. {passed ? `You can ${cfg.tagline.toLowerCase()}.` : `You need ${cfg.passMark}. Replay a game, then try the boss again.`}</p><div className="star-burst">{'⭐'.repeat(Math.max(1, Math.min(3, Math.ceil(score / total * 3))))}</div><div className="player-actions">{passed ? <button className="primary" onClick={() => go(dispatch, { screen: 'levelDone', level })}>See level complete <ChevronRight size={18} /></button> : <><button className="secondary" onClick={() => go(dispatch, { screen: 'trail', level })}>Back to trail</button><button className="primary" onClick={() => go(dispatch, { screen: 'boss', level })}>Try again</button></>}</div></section>; }

function LevelDone({ state, dispatch, level }) { const index = LEVEL_ORDER.indexOf(level); const next = LEVEL_ORDER[index + 1]; const cfg = LEVELS[level]; const remember = LESSONS[level].map((lesson) => lesson.remember); return <section className="completion-card card redesign-screen"><div className="completion-sticker">{cfg.icon}</div><div className="eyebrow">Level complete</div><h1>{cfg.island} is glowing!</h1><p>You learned:</p><div className="remember-grid">{remember.map((line) => <span key={line}><Check size={16} /> {line}</span>)}</div><div className="star-burst">⭐ ⭐ ⭐</div><div className="player-actions">{next ? <button className="primary" onClick={() => go(dispatch, { screen: 'trail', level: next })}>Next level: {LEVELS[next].label} <ChevronRight size={18} /></button> : <button className="primary" onClick={() => go(dispatch, { screen: 'certificate' })}>Get certificate <Sparkles size={18} /></button>}<button className="secondary" onClick={() => go(dispatch, { screen: 'home' })}>Back to map</button></div></section>; }

function Certificate({ state, dispatch }) { return <section className="certificate redesign-screen card"><div className="certificate-seal">🏆</div><div className="eyebrow">Fraction Isles</div><h1>Island Architect</h1><p>{state.nickname ? `${state.nickname}, ` : ''}you learned what fractions are, used them in real life, and solved multi-step problems.</p><div className="certificate-islands">☀️ 🌊 ⛰️</div><h3>“Look at the whole. Check the parts.”</h3><p className="muted">Total stars: ⭐ {totalStars(state)}</p><div className="player-actions"><button className="secondary" onClick={() => go(dispatch, { screen: 'home' })}><HomeIcon size={18} /> Back to map</button><button className="primary" onClick={() => window.print()}>Print certificate</button></div></section>; }

function Options({ options, selected, disabled, onSelect }) { return <div className="redesign-options" role="radiogroup">{options.map((option, index) => <button key={`${option}-${index}`} className={`redesign-option ${selected === index ? 'selected' : ''}`} disabled={disabled} onClick={() => onSelect(index)} role="radio" aria-checked={selected === index}>{renderFraction(option)}</button>)}</div>; }

function VisualStage({ kind, calm }) {
  const pieces = (count, shaded) => <div className="visual-bar">{Array.from({ length: count }, (_, i) => <i className={i < shaded ? 'shaded' : ''} key={i} />)}</div>;
  if (kind === 'whole') return <div className="visual-stage concept"><div className="whole-block">ONE WHOLE</div><div className="piece-block">ONE PIECE</div></div>;
  if (kind === 'equal') return <div className="visual-stage concept"><div><small>FAIR</small>{pieces(4, 4)}</div><div><small>NOT FAIR</small><div className="visual-bar unequal"><i className="shaded" /><i /><i className="shaded" /><i /></div></div></div>;
  if (kind === 'fraction' || kind === 'shade') return <div className="visual-stage fraction-stage">{pieces(kind === 'shade' ? 4 : 5, kind === 'shade' ? 3 : 2)}<strong>{kind === 'shade' ? '3 of 4' : '2 of 5'}</strong></div>;
  if (kind === 'equivalent' || kind === 'wall') return <div className="visual-stage twin-stage"><div>{pieces(2, 1)}<b>1/2</b></div><span>=</span><div>{pieces(4, 2)}<b>2/4</b></div><span>=</span><div>{pieces(8, 4)}<b>4/8</b></div></div>;
  if (kind === 'compare') return <div className="visual-stage compare-stage"><div><b>1/3</b>{pieces(3, 1)}</div><div><b>1/5</b>{pieces(5, 1)}</div></div>;
  if (kind === 'uses') return <div className="visual-stage uses-stage"><span>🍕<b>1/2</b></span><span>⏰<b>1/4</b></span><span>🔋<b>3/4</b></span><span>📏<b>1/2</b></span></div>;
  if (kind === 'cup') return <div className="visual-stage cup-stage"><div className="cup"><span /></div><b>1/2 full</b></div>;
  if (kind === 'add') return <div className="visual-stage add-stage"><div>{pieces(2, 1)}<b>1/2</b></div><span>+</span><div>{pieces(4, 1)}<b>1/4</b></div><span>=</span><strong>3/4</strong></div>;
  if (kind === 'groups') return <div className="visual-stage groups-stage">{Array.from({ length: 12 }, (_, i) => <i className={i < 9 ? 'shaded' : ''} key={i}>●</i>)}</div>;
  if (kind === 'clock') return <div className="visual-stage clock-stage"><div className="clock-face"><i /></div><b>15 · 30 · 45 minutes</b></div>;
  if (kind === 'area') return <div className="visual-stage area-stage">{Array.from({ length: 12 }, (_, i) => <i className={i < 6 ? 'shaded' : ''} key={i} />)}<b>2/3 × 3/4</b></div>;
  if (kind === 'divide') return <div className="visual-stage divide-stage"><span>WHOLE</span><span>WHOLE</span><span>WHOLE</span><b>÷ 1/4 = 12</b></div>;
  if (kind === 'bar') return <div className="visual-stage bar-stage"><span>1/3 spent</span><span>2/3 remains</span><b>whole</b></div>;
  if (kind === 'chance') return <div className="visual-stage chance-stage"><div>{Array.from({ length: 6 }, (_, i) => <i className={i < 2 ? 'shaded' : ''} key={i} />)}</div><b>2 of 6 → 1/3</b></div>;
  return <div className="visual-stage concept"><Sparkles size={48} /><b>Look, tap, explain.</b></div>;
}
