import React, { useEffect, useMemo, useReducer, useState } from 'react';
import { Check, ChevronLeft, ChevronRight, Lock, Map, Play, RotateCcw, Settings, Volume2, VolumeX, X } from 'lucide-react';
import { LEVELS, LEVEL_ORDER } from './config/levels.js';
import { CONTENT } from './content/v3.js';
import { makeInitialState } from './app/initialState.js';
import { reducer } from './app/reducer.js';
import { loadState, saveState } from './app/persistence.js';
import { allLevelsDone, levelProgress, levelUnlocked, nextNodeIndex, nodeStatus, phaseOfNode, phaseProgress, totalStars, trailOf } from './app/selectors.js';

const routeHash = (r) => r.screen === 'home' ? '#/' : r.screen === 'hub' ? `#/level/${r.level}` : r.screen === 'done' ? `#/done/${r.level}` : r.screen === 'certificate' ? '#/certificate' : `#/level/${r.level}/${r.screen}${r.index !== undefined ? `/${r.index + 1}` : ''}`;
const parseHash = () => { const bits = location.hash.slice(2).split('/').filter(Boolean); if (!bits.length) return { screen: 'home' }; if (bits[0] === 'certificate') return { screen: 'certificate' }; if (bits[0] === 'done') return { screen: 'done', level: bits[1] }; if (bits[0] === 'level' && LEVELS[bits[1]]) return bits[2] ? { screen: bits[2], level: bits[1], index: bits[3] ? Number(bits[3]) - 1 : undefined } : { screen: 'hub', level: bits[1] }; return { screen: 'home' }; };
const targetRoute = (id, node) => ({ screen: node.kind === 'lab' ? 'lab' : node.kind, level: id, index: node.kind === 'lab' || node.kind === 'game' ? node.index : undefined });
const same = (a, b) => a.length === b.length && a.every((v) => b.includes(v));

export default function App() {
  const [state, dispatch] = useReducer(reducer, undefined, () => loadState() || makeInitialState());
  const go = (route) => dispatch({ type: 'GO', route });
  useEffect(() => { saveState(state); history.replaceState(null, '', routeHash(state.route)); }, [state]);
  useEffect(() => { const onHash = () => { const route = parseHash(); if (route.screen === 'home' || route.screen === 'certificate' || route.screen === 'done' || (route.level && levelUnlocked(state, route.level))) go(route); }; addEventListener('hashchange', onHash); return () => removeEventListener('hashchange', onHash); }, [state.settings.unlockAll, state.levels]);
  const level = state.route.level;
  return <div className={`app ${state.settings.calmMotion ? 'calm' : ''}`} data-level={level || 'beginner'}>
    <PatternDefs /><TopBar state={state} dispatch={dispatch} go={go} />
    <main className="main">{state.route.screen === 'home' ? <Home state={state} go={go} dispatch={dispatch} /> : <RouteView state={state} go={go} dispatch={dispatch} />}</main>
    <button className="audio-toggle" onClick={() => dispatch({ type: 'TOGGLE_SETTING', key: 'audio' })} aria-label="Toggle narration">{state.settings.audio ? <Volume2 /> : <VolumeX />}</button>
  </div>;
}

function TopBar({ state, dispatch, go }) { const [open, setOpen] = useState(false); return <><header className="topbar"><button className="brand" onClick={() => go({ screen: 'home' })}><span className="brand-mark">⅓</span>Fraction Isles</button>{state.route.level && <PhaseNav state={state} go={go} /> }<div className="stats"><span>⭐ {totalStars(state)}</span><span>✨ {state.scoring.xp}</span><button className="icon-button" onClick={() => setOpen(true)} aria-label="Settings"><Settings /></button></div></header>{open && <SettingsModal state={state} dispatch={dispatch} close={() => setOpen(false)} />}</>; }
function SettingsModal({ state, dispatch, close }) { return <div className="modal" role="presentation"><section className="panel settings" role="dialog" aria-modal="true"><button className="close" onClick={close}><X /></button><p className="eyebrow">Grown-ups</p><h2>Settings</h2>{[['calmMotion', 'Calm motion'], ['unlockAll', 'Unlock all levels'], ['audio', 'Audio']].map(([key, label]) => <label className="setting" key={key}>{label}<button className={state.settings[key] ? 'on' : ''} onClick={() => dispatch({ type: 'TOGGLE_SETTING', key })}>{state.settings[key] ? 'On' : 'Off'}</button></label>)}<button className="secondary" onClick={() => { dispatch({ type: 'RESET' }); close(); }}><RotateCcw /> Reset progress</button></section></div>; }
function PhaseNav({ state, go }) { const id = state.route.level; const active = state.route.screen === 'lab' ? 'simulate' : state.route.screen === 'game' ? 'play' : state.route.screen === 'boss' || state.route.screen === 'explain' || state.route.screen === 'done' ? 'reflect' : state.route.screen; const paths = { wonder: { screen: 'wonder' }, story: { screen: 'story' }, simulate: { screen: 'lab', index: 0 }, play: { screen: 'game', index: 0 }, reflect: { screen: 'boss' } }; return <nav className="phase-nav" aria-label="Level phases">{Object.entries(paths).map(([phase, route]) => { const [done, total] = phaseProgress(state, id)[phase]; const available = done > 0 || phase === active || state.settings.unlockAll || (phase === 'wonder'); return <button className={phase === active ? 'active' : done === total ? 'done' : ''} disabled={!available} onClick={() => go({ ...route, level: id })} key={phase}>{phase}</button>; })}</nav>; }

function Home({ state, go, dispatch }) { const [name, setName] = useState(state.nickname); const unlocked = LEVEL_ORDER.filter((id) => levelUnlocked(state, id)); const id = unlocked[unlocked.length - 1]; const n = trailOf(id)[nextNodeIndex(state, id)]; return <section className="screen home"><div className="hero panel"><div><p className="eyebrow">Sunrise Lagoon</p><h1>Rebuild the Lighthouse.</h1><p>Wonder, explore, play, and explain fractions across three bright islands.</p>{!state.nickname && <div className="name-row"><input value={name} maxLength="12" aria-label="Optional nickname" placeholder="Your name (optional)" onChange={(e) => setName(e.target.value)} /><button className="secondary" onClick={() => dispatch({ type: 'SET_NAME', name })}>Save</button></div>}<button className="primary" onClick={() => go(targetRoute(id, n))}><Play /> Continue <small>{n.kind === 'lab' ? `Lab ${'ABCD'[n.index]}` : n.kind}</small></button></div><Scene level="beginner" icon="🗼" /></div><div className="section-title"><div><p className="eyebrow">Level Map</p><h2>Choose an island</h2></div><span>Wonder · Story · 4 labs · 4 games · Boss</span></div><div className="map-grid">{LEVEL_ORDER.map((id) => <LevelCard key={id} id={id} state={state} go={go} />)}</div></section>; }
function LevelCard({ id, state, go }) { const cfg = LEVELS[id]; const p = levelProgress(state, id); const unlocked = levelUnlocked(state, id); const phases = phaseProgress(state, id); return <article className={`panel level-card ${unlocked ? '' : 'locked'}`} data-level={id}><Scene level={id} icon={cfg.icon} compact /><p className="eyebrow">{cfg.label} · {cfg.grades}</p><h2>{cfg.island}</h2><p>{cfg.tagline}</p><div className="phase-ring">{Object.entries(phases).map(([k, [d, t]]) => <i className={d === t ? 'filled' : d ? 'partial' : ''} title={`${k} ${d}/${t}`} key={k} />)}</div><div className="progress"><span style={{ width: `${p.pct}%` }} /></div><small>{unlocked ? `${p.done} of ${p.total} stops` : 'Finish the earlier island first.'}</small><button className={unlocked ? 'primary' : 'secondary'} disabled={!unlocked} onClick={() => go({ screen: 'hub', level: id })}>{unlocked ? 'Open island' : <><Lock /> Locked</>}</button></article>; }
function RouteView({ state, go, dispatch }) { const r = state.route; if (r.screen === 'hub') return <Hub state={state} go={go} />; if (r.screen === 'wonder') return <Wonder id={r.level} go={go} dispatch={dispatch} />; if (r.screen === 'story') return <Story id={r.level} go={go} dispatch={dispatch} />; if (r.screen === 'lab') return <Lab id={r.level} index={r.index || 0} state={state} go={go} dispatch={dispatch} />; if (r.screen === 'game') return <Game id={r.level} index={r.index || 0} state={state} go={go} dispatch={dispatch} />; if (r.screen === 'boss') return <Boss id={r.level} go={go} dispatch={dispatch} />; if (r.screen === 'explain') return <Explain id={r.level} go={go} />; if (r.screen === 'done') return <Done id={r.level} state={state} go={go} />; return <Certificate state={state} go={go} />; }

function Hub({ state, go }) { const id = state.route.level; const cfg = LEVELS[id]; const nodes = trailOf(id); const open = (n, i) => nodeStatus(state, id, i) !== 'locked' && go(targetRoute(id, n)); return <section className="screen"><button className="back" onClick={() => go({ screen: 'home' })}><ChevronLeft /> Map</button><div className="hub-title"><div><p className="eyebrow">{cfg.label} · {cfg.island}</p><h1>{cfg.tagline}</h1></div><LighthouseMeter state={state} /></div><div className="hub-path">{nodes.map((n, i) => { const status = nodeStatus(state, id, i); const label = n.kind === 'lab' ? `Lab ${'ABCD'[n.index]}` : n.kind === 'game' ? CONTENT[id].games[n.index].title : n.kind; const icon = n.kind === 'lab' ? CONTENT[id].labs[n.index].icon : n.kind === 'game' ? CONTENT[id].games[n.index].icon : n.kind === 'wonder' ? '✦' : n.kind === 'story' ? '📖' : '🏆'; return <button key={`${n.kind}${i}`} className={`node ${status}`} onClick={() => open(n, i)}><b>{status === 'done' ? <Check /> : icon}</b><small>{label}</small></button>; })}</div><div className="panel what"><h3>What you’ll learn</h3>{CONTENT[id].labs.map((l) => <span key={l.id}>{l.icon} {l.remember}</span>)}</div></section>; }
function LighthouseMeter({ state }) { return <div className="lighthouse-meter" aria-label="Lighthouse progress">🗼 {LEVEL_ORDER.map((id) => <span key={id} className={state.levels[id].boss.done ? 'lit' : ''}>●</span>)}</div>; }

function Wonder({ id, go, dispatch }) { const [beat, setBeat] = useState(0); const [guess, setGuess] = useState([]); const w = CONTENT[id].wonder; const b = w.beats[beat]; const next = () => { if (beat === 2) { dispatch({ type: 'WONDER_COMPLETE', level: id }); go({ screen: 'story', level: id }); } else setBeat(beat + 1); }; return <section className="wonder screen"><Scene level={id} icon={beat === 0 ? '🗼' : beat === 1 ? '🍕' : '✨'} /><div className="wonder-copy"><p className="eyebrow">Wonder · {id}</p><h1>{beat === 0 ? w.title : b.headline}</h1><p>{beat === 0 ? w.tagline : b.narration}</p>{beat === 1 && <><FractionBar parts={4} shaded={guess.length} selected={guess} onToggle={(i) => setGuess((old) => old.includes(i) ? old.filter((x) => x !== i) : [...old, i])} label="Make your prediction" /><p className="otto">🦦 There is no score for a guess.</p></>}{beat === 0 ? <button className="primary" onClick={next}>Begin ✨</button> : <button className="primary" onClick={next}>{beat === 1 ? b.go : b.cta} <ChevronRight /></button>}<button className="skip" onClick={() => beat < 2 ? setBeat(2) : next()}>Skip ▶</button></div></section>; }
function Story({ id, go, dispatch }) { const [index, setIndex] = useState(0); const item = CONTENT[id].story[index]; const next = () => { if (index === 3) { dispatch({ type: 'STORY_COMPLETE', level: id }); go({ screen: 'lab', level: id, index: 0 }); } else setIndex(index + 1); }; return <section className="screen story"><ArtSlot level={id} panel={index} icon={item[2]} /><div className="story-copy"><p className="eyebrow">Story · {index + 1} / 4</p><h1>{item[0]}</h1><p>{item[1]}</p><button className="hotspot">👆 Tap the glowing thing {item[2]}</button><p className="next-lab">Next: {item[3]}</p><div className="story-actions"><button className="secondary" disabled={!index} onClick={() => setIndex(index - 1)}>Back</button><button className="primary" onClick={next}>{index === 3 ? 'Start Lab A' : 'Next'} <ChevronRight /></button></div></div></section>; }
function ArtSlot({ level, panel, icon }) { const [missing, setMissing] = useState(false); const src = `/assets/story/${level}-${panel + 1}.webp`; return <div className="art-slot">{!missing && <img src={src} onError={() => setMissing(true)} alt="Story scene" />}{missing && <Scene level={level} icon={icon} />}</div>; }
function Scene({ level, icon, compact = false }) { return <div className={`scene ${compact ? 'compact' : ''}`} data-level={level}><span className="scene-sun">{level === 'advanced' ? '✦' : '☀'}</span><span className="scene-icon">{icon}</span><span className="scene-water">≈ ≈ ≈</span></div>; }

function Lab({ id, index, state, go, dispatch }) { const lab = CONTENT[id].labs[index]; const [phase, setPhase] = useState('explore'); const [parts, setParts] = useState(lab.explore.parts); const [marked, setMarked] = useState([]); const [discover, setDiscover] = useState([]); const [guided, setGuided] = useState(0); const [check, setCheck] = useState(0); const [selected, setSelected] = useState(null); const [feedback, setFeedback] = useState(''); const add = (key) => setDiscover((old) => old.includes(key) ? old : [...old, key]); const required = lab.explore.checklist.filter((x) => x.required).length; const toggle = (i) => { setMarked((old) => old.includes(i) ? old.filter((x) => x !== i) : [...old, i]); add('tap'); add('shade'); add('read'); };
  const reset = () => { setParts(lab.explore.parts); setMarked([]); setDiscover([]); };
  const guideDone = marked.length >= Math.min(guided + 1, parts); const answer = lab.checkin[check]; const submit = () => { const picked = answer.options.find((o) => o.id === selected); if (selected === answer.correct) { if (check === 1) setPhase('complete'); else { setCheck(1); setSelected(null); setFeedback('Lovely thinking — next check-in!'); } } else { dispatch({ type: 'MISCONCEPTION', tag: picked?.tag || 'UNKNOWN' }); setFeedback(picked?.tag === 'NOT_SIMPLEST' ? 'Right amount! Can you make bigger groups?' : 'Look again. Count the equal parts.'); } };
  const complete = () => { dispatch({ type: 'LAB_COMPLETE', level: id, index }); go(index === 3 ? { screen: 'game', level: id, index: 0 } : { screen: 'lab', level: id, index: index + 1 }); };
  return <section className="screen lab"><button className="back" onClick={() => go({ screen: 'hub', level: id })}><X /> Exit</button><LabTabs id={id} index={index} state={state} go={go} /><div className="lab-grid"><aside className="panel checklist"><p className="eyebrow">Discovery checklist</p>{lab.explore.checklist.map((item) => <span className={discover.includes(item.key) ? 'checked' : ''} key={item.key}>{discover.includes(item.key) ? '✓' : '○'} {item.label}</span>)}<p className="otto">🦦 {id === 'beginner' ? 'Are the pieces equal?' : id === 'builder' ? 'Are the pieces the same size?' : 'Does the answer make sense?'}</p></aside><section className="panel lab-stage"><p className="eyebrow">Lab {lab.letter} · {phase}</p><h1>{lab.title}</h1><p>{phase === 'explore' ? lab.intro.text : phase === 'guided' ? lab.guided[guided].goal : phase === 'checkin' ? answer.prompt : lab.remember}</p>{phase !== 'complete' && <><div className="stepper"><button onClick={() => { setParts((x) => Math.max(2, x - 1)); add('change'); }}>−</button><strong>{parts} equal parts</strong><button onClick={() => { setParts((x) => Math.min(12, x + 1)); add('change'); }}>+</button></div><FractionBar parts={parts} shaded={marked.length} selected={marked} onToggle={toggle} label="Fraction laboratory model" /><div className="readout"><Frac n={marked.length} d={parts} /> <span>{marked.length} of {parts} parts coloured</span></div></>}{phase === 'guided' && <div className="task-actions"><button className="secondary" onClick={() => setMarked(Array.from({ length: Math.min(guided + 1, parts) }, (_, i) => i))}>Show me</button><button className="primary" disabled={!guideDone} onClick={() => { if (guided === lab.guided.length - 1) setPhase('checkin'); else { setGuided(guided + 1); setMarked([]); } }}>I did it <ChevronRight /></button></div>}{phase === 'checkin' && <><Choices question={answer} selected={selected} onSelect={setSelected} /><p className="feedback">{feedback}</p><button className="primary" disabled={!selected} onClick={submit}>Check</button></>}{phase === 'complete' && <div className="concept"><b>{lab.icon}</b><h2>Concept unlocked!</h2><p>{lab.remember}</p><button className="primary" onClick={complete}>{index === 3 ? 'Start Games' : 'Next Lab'} <ChevronRight /></button></div>}<div className="lab-footer">{phase === 'explore' && <button className="primary" disabled={discover.length < required} onClick={() => setPhase('guided')}>Continue to Guided <ChevronRight /></button>}<button className="secondary" onClick={reset}>↺ Reset</button></div></section></div></section>; }
function LabTabs({ id, index, state, go }) { return <div className="lab-tabs">{CONTENT[id].labs.map((l, i) => <button key={l.id} className={i === index ? 'active' : state.levels[id].labs[i] ? 'done' : ''} disabled={i > index && !state.levels[id].labs[i]} onClick={() => go({ screen: 'lab', level: id, index: i })}>{l.letter} {l.title}</button>)}</div>; }
function FractionBar({ parts, shaded, selected, onToggle, label }) { const all = selected || Array.from({ length: shaded }, (_, i) => i); return <div className="fraction-bar" role="group" aria-label={label}>{Array.from({ length: parts }, (_, i) => <button key={i} className={all.includes(i) ? 'shaded' : ''} onClick={() => onToggle?.(i)} aria-label={`Part ${i + 1} of ${parts}`} />)}</div>; }
function Frac({ n, d }) { return <span className="frac" aria-label={`${n} over ${d}`}><b>{n}</b><i /><b>{d}</b></span>; }
function Choices({ question, selected, onSelect }) { return <div className="choices">{question.options.map((o) => <button className={selected === o.id ? 'selected' : ''} key={o.id} onClick={() => onSelect(o.id)}>{o.text}</button>)}</div>; }

function Game({ id, index, state, go, dispatch }) { const game = CONTENT[id].games[index]; const [round, setRound] = useState(0); const [marked, setMarked] = useState([]); const [selected, setSelected] = useState(null); const [checked, setChecked] = useState(false); const [score, setScore] = useState(0); const [help, setHelp] = useState(!state.seen[`game:${id}:${index}`]); const item = game.rounds[round]; const buildReady = same(marked, Array.from({ length: item.visual.shaded }, (_, i) => i)); const finish = () => { dispatch({ type: 'GAME_COMPLETE', level: id, index, correct: score + (selected === item.correct ? 1 : 0), total: game.rounds.length }); go(index === 3 ? { screen: 'boss', level: id } : { screen: 'game', level: id, index: index + 1 }); }; const check = () => { if (!buildReady) { setChecked('Build the picture first.'); return; } setChecked(true); if (selected !== item.correct) { const o = item.options.find((x) => x.id === selected); if (o?.tag) dispatch({ type: 'MISCONCEPTION', tag: o.tag }); } }; const next = () => { if (round === game.rounds.length - 1) finish(); else { setScore(score + (selected === item.correct ? 1 : 0)); setRound(round + 1); setMarked([]); setSelected(null); setChecked(false); } };
  return <section className="screen game"><button className="back" onClick={() => go({ screen: 'hub', level: id })}><X /> Exit</button>{help && <div className="modal"><section className="panel how"><h2>How to play</h2><p>Build the fraction model by tapping pieces. Then choose the matching answer. Your first answer earns the score.</p><button className="primary" onClick={() => { setHelp(false); dispatch({ type: 'MARK_SEEN', key: `game:${id}:${index}` }); }}>Let’s play!</button></section></div>}<div className="game-head"><div><p className="eyebrow">Play · {game.icon} {game.title}</p><h1>Round {round + 1} of {game.rounds.length}</h1></div><span>⭐ {score}</span></div><section className="panel game-stage"><p>{item.prompt}</p><FractionBar parts={item.visual.parts} shaded={marked.length} selected={marked} onToggle={(i) => setMarked((old) => old.includes(i) ? old.filter((x) => x !== i) : [...old, i])} label="Build the game model" /><div className="readout"><Frac n={marked.length} d={item.visual.parts} /></div><Choices question={item} selected={selected} onSelect={setSelected} /><p className="feedback">{typeof checked === 'string' ? checked : checked ? selected === item.correct ? 'Great work! That model matches.' : 'Look again. The picture gives you a clue.' : 'Build the picture, then choose.'}</p>{checked ? <button className="primary" onClick={next}>{round === game.rounds.length - 1 ? 'Finish game' : 'Next round'} <ChevronRight /></button> : <button className="primary" disabled={!selected} onClick={check}>Check ✓</button>}</section></section>; }
function Boss({ id, go, dispatch }) { const qs = CONTENT[id].boss; const [index, setIndex] = useState(0); const [selected, setSelected] = useState(null); const [score, setScore] = useState(0); const [checked, setChecked] = useState(false); const q = qs[index]; const submit = () => { if (!checked) { setChecked(true); if (selected !== q.correct) { const opt = q.options.find((o) => o.id === selected); if (opt?.tag) dispatch({ type: 'MISCONCEPTION', tag: opt.tag }); } return; } const nextScore = score + (selected === q.correct ? 1 : 0); if (index === qs.length - 1) { dispatch({ type: 'BOSS_COMPLETE', level: id, correct: nextScore, total: qs.length }); nextScore >= LEVELS[id].passMark ? go({ screen: 'explain', level: id }) : go({ screen: 'hub', level: id }); } else { setScore(nextScore); setIndex(index + 1); setSelected(null); setChecked(false); } }; return <section className="screen boss"><div className="game-head"><div><p className="eyebrow">Reflect · Boss Challenge</p><h1>Rebuild the lamp</h1></div><span>{index + 1} / {qs.length}</span></div><div className="lamp"><span style={{ width: `${((index + 1) / qs.length) * 100}%` }} /></div><section className="panel game-stage"><FractionBar parts={q.visual.parts} shaded={q.visual.shaded} label="Boss fraction model" /><h2>{q.prompt}</h2><Choices question={q} selected={selected} onSelect={setSelected} /><p className="feedback">{checked ? selected === q.correct ? 'A lamp facet lights up!' : 'Look again. Use the picture clue.' : 'Each answer restores one lamp facet.'}</p><button className="primary" disabled={!selected} onClick={submit}>{checked ? (index === qs.length - 1 ? 'See result' : 'Next') : 'Light facet'}</button></section></section>; }
function Explain({ id, go }) { const [placed, setPlaced] = useState([]); const tiles = CONTENT[id].explain; const next = () => { const wanted = tiles[placed.length]; if (wanted) setPlaced([...placed, wanted]); }; return <section className="screen explain panel"><p className="eyebrow">Reflect · Explain it</p><h1>Put the steps in order</h1><p>Tap each next step to explain the idea.</p><div className="tiles">{tiles.map((t, i) => <button className={placed.includes(t) ? 'locked' : ''} disabled={placed.includes(t)} onClick={() => t === tiles[placed.length] && next()} key={t}>{placed.includes(t) ? '✓ ' : ''}{t}</button>)}</div>{placed.length === tiles.length && <button className="primary" onClick={() => go({ screen: 'done', level: id })}>Finish level <ChevronRight /></button>}</section>; }
function Done({ id, state, go }) { const cfg = LEVELS[id]; const next = LEVEL_ORDER[LEVEL_ORDER.indexOf(id) + 1]; return <section className="screen done panel"><Scene level={id} icon="🗼" /><p className="eyebrow">Level complete</p><h1>{cfg.island} is glowing!</h1><p>You can now:</p><div className="remember">{CONTENT[id].labs.map((lab) => <span key={lab.id}>✓ {lab.remember}</span>)}</div><button className="primary" onClick={() => go(next ? { screen: 'hub', level: next } : { screen: 'certificate' })}>{next ? `Next: ${LEVELS[next].label}` : 'Get certificate'} <ChevronRight /></button><button className="secondary" onClick={() => go({ screen: 'home' })}>Back to map</button></section>; }
function Certificate({ state, go }) { return <section className="screen certificate panel"><div>🏆</div><p className="eyebrow">Fraction Isles</p><h1>Island Architect</h1><p>{state.nickname ? `${state.nickname}, ` : ''}you rebuilt the Lighthouse and explained fractions with care.</p><p className="big">☀️ 🌊 ⛰️</p><p>Total stars: ⭐ {totalStars(state)}</p><button className="primary" onClick={() => print()}>Print certificate</button><button className="secondary" onClick={() => go({ screen: 'home' })}>Back to map</button>{!allLevelsDone(state) && <p>Keep exploring to light every lamp.</p>}</section>; }
function PatternDefs() { return <svg aria-hidden="true" className="patterns"><defs>{[2,3,4,5,6,8,10,12].map((n) => <pattern id={`den-${n}`} key={n} width="8" height="8" patternUnits="userSpaceOnUse"><path d={n % 2 ? 'M0 8L8 0' : 'M0 4H8'} stroke="currentColor" strokeWidth="1" /></pattern>)}</defs></svg>; }
